---
apiVersion: v1
kind: Service
metadata:
  name: qwen2
spec:
  selector:
    app: qwen2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen2
spec:
  selector:
    matchLabels:
      app: qwen2
  template:
    metadata:
      labels:
        app: qwen2
    spec:
      runtimeClassName: ollama-shim
      containers:
        - name: qwen2
          image: svlcastai/qwen2-ubuntu:0.5b
          imagePullPolicy: IfNotPresent
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0:8080"
            - name: OLLAMA_MODEL_NAME
              value: "qwen2"
            - name: OLLAMA_MODEL_PATH
              value: "/Qwen2-0.5B-Instruct.Q5_K_M.gguf"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
