apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ollama-ui-role.yaml
- ollama-ui-service.yaml
- ollama-ui-deployment.yaml
- ollama-ui-service-account.yaml

images:
- name: ollama-ui
  newName: ghcr.io/kubeflow/ollama/ui
  newTag: latest
