---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ollama-ui-services-reader
rules:
- apiGroups:
    - ''
  resources:
    - services
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ollama-ui-services-reader-binding
subjects:
- kind: ServiceAccount
  name: ollama-ui
roleRef:
  kind: ClusterRole
  name: ollama-ui-services-reader
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ollama-ui-deployments-manager
rules:
- apiGroups:
    - ''
  resources:
    - deployments
  verbs:
    - get
    - list
    - watch
    - create
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ollama-ui-deployments-manager-binding
subjects:
- kind: ServiceAccount
  name: ollama-ui
roleRef:
  kind: ClusterRole
  name: ollama-ui-deployments-manager
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ollama-retrieve-clusterrolebindings
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ollama-retrieve-clusterrolebindings-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ollama-retrieve-clusterrolebindings
subjects:
- kind: ServiceAccount
  name: ollama-ui
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ollama-create-sars
rules:
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ollama-create-sars-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ollama-create-sars
subjects:
- kind: ServiceAccount
  name: ollama-ui
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ollama-ui-configmaps-reader
rules:
- apiGroups:
    - ''
  resources:
    - configmaps
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ollama-ui-configmaps-reader-binding
subjects:
- kind: ServiceAccount
  name: ollama-ui
roleRef:
  kind: ClusterRole
  name: ollama-ui-configmaps-reader
  apiGroup: rbac.authorization.k8s.io