apiVersion: v1
kind: Service
metadata:
  name: ollama-ui-service
  labels:
    app: ollama-ui
    run: ollama-ui
spec:
  selector:
    app: ollama-ui
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
