apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../integrated
- virtual-service.yaml
- destination-rule-ui.yaml
- authorization-policy-ui.yaml

patches:
  - path: ollama-ui-service.yaml
    target:
      version: v1
      kind: Service
      name: ollama-ui-service

namespace: kubeflow