apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ollama-ui-deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: ollama-ui
